x-common-variables: &common-variables
    WWWUSER: '${WWWUSER:-1000}'
    WWWGROUP: '${WWWGROUP:-1000}'
    APP_ENV: '${APP_ENV:-local}'
    APP_DEBUG: '${APP_DEBUG:-false}'

services:
    nginx:
        image: nginx:alpine
        container_name: "laravel_nginx"
        ports:
            - '${APP_PORT:-80}:80'
            - '${APP_SSL_PORT:-443}:443'
        volumes:
            - '.:/var/www/html'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
            - 'sail-php-socket:/var/run/php'
        networks:
            - sail

    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                PHP_VERSION: '${PHP_VERSION:-8.4}'
                NODE_VERSION: '${NODE_VERSION:-20}'
        container_name: "laravel_php"
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            <<: *common-variables
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            PHP_FPM_LISTEN: '/var/run/php/php-fpm.sock'
        volumes:
            - '.:/var/www/html'
            - 'sail-php-socket:/var/run/php'
            - './docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf'
        networks:
            - sail

    frontend:
        image: node:20-alpine
        container_name: "laravel_front"
        working_dir: /app
        volumes:
            - ./resources/frontend:/app
        command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
        ports:
            - "3000:3000"
        networks:
            - sail
        depends_on:
            - php

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS}'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail

    valkey:
        image: 'valkey/valkey:alpine'
        ports:
            - '${FORWARD_VALKEY_PORT:-6379}:6379'
        volumes:
            - 'sail-valkey:/data'
        networks:
            - sail

    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - 'sail-meilisearch:/meili_data'
        networks:
            - sail

    rabbitmq:
        image: 'rabbitmq:4-management-alpine'
        hostname: rabbitmq
        ports:
            - '${FORWARD_RABBITMQ_PORT:-5672}:5672'
            - '${FORWARD_RABBITMQ_DASHBOARD_PORT:-15672}:15672'
        environment:
            RABBITMQ_HOST: '%'
            RABBITMQ_USER: '${RABBITMQ_USER}'
            RABBITMQ_PASSWORD: '${RABBITMQ_PASSWORD}'
            RABBITMQ_VHOST: '${RABBITMQ_VHOST}'
            RABBITMQ_QUEUE: '${RABBITMQ_QUEUE}'
        volumes:
            - 'sail-rabbitmq:/var/lib/rabbitmq'
        networks:
            - sail

    adminer:
        container_name: laravel-adminer
        image: adminer
        depends_on:
            - mysql
        environment:
            - ADMINER_DEFAULT_SERVER=${DB_HOST}
        ports:
            - "8080:8080"
        networks:
            - sail

networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-valkey:
        driver: local
    sail-meilisearch:
        driver: local
    sail-rabbitmq:
        driver: local
    sail-php-socket:
        driver: local
